name: Demo
description: A sample command-line dart application.
version: 0.0.1
author: Sasha Prokhorenko <djminikin@gmail.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0

dev_dependencies:
  test: ^1.0.0
